package api
//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ModelAPI.proto

@kotlin.jvm.JvmSynthetic
public inline fun bytes(block: BytesKt.Dsl.() -> kotlin.Unit): ModelAPIOuterClass.Bytes =
  BytesKt.Dsl._create(ModelAPIOuterClass.Bytes.newBuilder()).apply { block() }._build()
public object BytesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ModelAPIOuterClass.Bytes.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ModelAPIOuterClass.Bytes.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ModelAPIOuterClass.Bytes = _builder.build()

    /**
     * <code>bytes body = 1;</code>
     */
    public var body: com.google.protobuf.ByteString
      @JvmName("getBody")
      get() = _builder.getBody()
      @JvmName("setBody")
      set(value) {
        _builder.setBody(value)
      }
    /**
     * <code>bytes body = 1;</code>
     */
    public fun clearBody() {
      _builder.clearBody()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ModelAPIOuterClass.Bytes.copy(block: BytesKt.Dsl.() -> kotlin.Unit): ModelAPIOuterClass.Bytes =
  BytesKt.Dsl._create(this.toBuilder()).apply { block() }._build()
